import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useMemo, useState } from "react";

const Home: NextPage = () => {
  const [height, setHeight] = useState(150);
  const [weight, setWeight] = useState(50);

  function onHeightChange(event) {
    const heightValue = event.target.value;
    setHeight(heightValue);
  }

  function onWeightChange(event) {
    const weightVaule = event.target.value;
    setWeight(weightVaule);
  }

  const output = useMemo(() => {
    const calculatedHeight = height / 100;
    return (weight / (calculatedHeight * calculatedHeight)).toFixed(1);
  }, [weight, height]);

  return (
    <div className={styles.container}>
      <Head>
        <title>BMI Calculator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>BMI Calculator</h1>
        <div>
          <p>Weight: {weight} kg</p>
          <input
            onChange={onWeightChange}
            type="range"
            step="1"
            min="20"
            max="200"
          />

          <p>Height: {height} cm</p>
          <input onChange={onHeightChange} type="range" min="100" max="299" step="1" />
        </div>

        <div>
          <p>Your BMI is</p>
          <p>{output}</p>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
